#!/bin/bash

userID=$1

if [$2 -e ""] 
then
    nextPageToken=""
else
    nextPageToken="&pagination_token=$2"
fi

curl -H "Authorization: Bearer $bearerToken" \
"https://api.twitter.com/2/users/$userID/tweets?max_results=100$nextPageToken&tweet.fields=created_at" \
> "./database/retrieve/raw.json"
